import type { Metadata } from "next";
import { Lexend, Righteous } from "next/font/google";
import "./globals.css";
// Components
import { Container, CustomNavbar, Providers } from "./common";

const lexend = Lexend({ subsets: ["latin"], variable: "--font-lexend" });

const righteous = Righteous({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${lexend.className}`}>
        <Providers>
          <CustomNavbar />
          <Container> {children}</Container>
        </Providers>
      </body>
    </html>
  );
}
